### ISSUE TITLE
output files should be concatenated

### ISSUE THREAD

**Issue by jbrestel** [VEuPathDB/tRNAScan#2]
the tRNAScan process declares an output which is published BUT shouldn't this be concatenated first?  i didn't test run but it is unclear why this wouldn't clobber the output files

**Comment by rdemko2332** [comment]
Output files are now named depending on their sequence identifier. This stops the clobbering of output files.

**Comment by rdemko2332** [comment]
With new functionality, output files are concatenated and only container a singular header.
